### ISSUE TITLE
Trouble installing and enabling the extension

### ISSUE THREAD

**Issue by irvng-wav** [flexagoon/rounded-window-corners#1]
Hello! When I tried to install the extension from source I got the following error:

```shell
yarn install
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.13s.
npx tsc --outDir ./_build
bash: línea 1: npx: orden no encontrada (order not found)
error: Recipe `build` failed on line 10 with exit code 127
``` 

I'm running Arch Linux and I previously installed all the dependencies needed: `nodejs` `yarn` `gettext` and `just`.

After googling for a few minutes I found out that I also needed the `npm` package, so I installed it and after that the compilation and installation was successful.

But then, when trying to enable the extension from GNOME Extensions I get the following error:
```shell
ImportError: Unknown module: '@global'
``` 
Because of that I can't turn on the extension.

Thanks in advance. Looking forward to having rounded window corners in my system!

**Comment by flexagoon** [comment]
@irvng-wav looks like I forgot some external dependencies while writing the new build instruction.

The npm issue will be resolved anyway as I'll probably replace yarn with npm, since more people have npm installed and this project has very few dev dependencies, so yarn doesn't really have any benefits.

As for the `@global` thing, the old JS-based build system did some patching of import statements, I assumed that it's no longer necessary with the new GNOME 45 imports, but it seems like it's still needed in one place. I'll probably just fix the import manually.

Ill fix the issues later today when I'm at my computer.

**Comment by flexagoon** [comment]
For now, you can just build the extension from the old commit

https://github.com/flexagoon/rounded-window-corners/tree/383bfcd335c94c10a53ee6d7bf9ea691458de7a2

I didn't make any functionality changes after that, just some refactoring to make the project smaller and easier to maintain, so you won't see any differences
