### ISSUE TITLE
compiz window effect incompatibility

### ISSUE THREAD

**Issue by Cm4nXD** [flexagoon/rounded-window-corners#14]
shadow doesn't move when using compiz window effect extension.

Potentially you could make it so that it hides the shadow when moving a window? Similar to the compiz alike magic lamp effect?

**Comment by Yumeo0** [comment]
For me it just cuts off the windows in weird ways when I move them.

https://github.com/flexagoon/rounded-window-corners/assets/60485613/89903ab7-b264-47be-9b79-98a55404d3f0

**Comment by Yumeo0** [comment]
I just found out that the error is different for different applications. Firefox gets cut off and VSCodium has the weird shadow bug that the original poster mentioned.

**Comment by flexagoon** [comment]
I don't think it will be possible to implement compatibility with this effect. This effect draws a custom shadow which is rectangular, so it can't adjust for the weird shape of wobbly windows. I don't know if the compiz effect has some sort of way to get the window shape (I think it doesn't), but even if it does, writing a shader that can draw complex shadows like this is very hard and not something I can do.

**Comment by k2helix** [comment]
Maybe disabling shadow opacity when moving a window and compiz windows effect is enabled could be a workaround? Right now, in order to use both plugins shadows opacity must be set to 0, which leads to confusion when trying to distinguish windows. So if this could be done only when the window is moving, it would be way easier.
