### ISSUE TITLE
Please simplify the installation

### ISSUE THREAD

**Issue by Humpix** [flexagoon/rounded-window-corners#16]
Thank you for keeping this extension alive. Unfortunately, Gnome has not yet managed to create a standardised design...

But... I needed 2 Youtube videos and a Github account to be able to even download the file at all. Installing it doesn't work either, because the command gnome-extensions install filename.zip doesn't work or the extension doesn't appear. And gnome-extensins list doesn't show it either. But a new attempt ends in the error that the extension is installed.

As a non-programmer, I sadly fail to follow the instructions completely. Perhaps you could make the extension a little more accessible for ordinary people?

BR, and thanks!
Mathias

**Comment by flexagoon** [comment]
There is currently a bug in the "Blur My Shell" extension when it's used together with rounded window corners. Because of that, I added a workaround to this extension. However, that workaround will not pass the review process of extensions.gnome.org

I already submitted a proper fix to Blur My Shell, and it will come out in the next version of BMS. Once it is released, I'll be able to publish this extension to https://extensions.gnome.org as well.

You should wait for Blur My Shell to make a new release or ping the maintainer here saying that you need a new release:

https://github.com/aunetx/blur-my-shell/pull/588

Also, if you want to install this right now, you're not supposed to use the `gnome-extensions install` command. The installation instructions are in the readme file. You can install all dependencies with your package manager (eg. `apt install`), and then just copy paste the specified command.

**Comment by flexagoon** [comment]
Also, where were you downloading the zip file from? Make sure you're downloading it from here: https://github.com/flexagoon/rounded-window-corners/actions/workflows/build.yml, and not just from the "download zip" button on github
